// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "bean":return img`
................
................
.....eeeeee.....
....eeeeeeee....
...eeeeeeeeee...
..eeeeeeeeeee...
..eeeeeeeeeee...
..eeeeeeeeee....
..eeeeeeeeee....
..eeeeeeeee.....
..eeeeeeeee.....
..eeeeeeeee.....
..eeeeeeeeee....
..eeeeeeeeee....
..eeeeeeeeeee...
..eeeeeeeeeee...
...eeeeeeeeee...
....eeeeeeee....
.....eeeeee.....
................
................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
